"""
Group 2, Figure B3: Four-wave-mixing wavelength conversion efficiency
======================================================================

Drive the FM with a strong pump at omega_p ~ omega_1 plus a weak signal at
omega_s = omega_p - Omega. The Kerr nonlinearity (native, cascade, or both)
mixes them to produce an idler at omega_i = omega_p + Omega.

To extract idler in our single-frequency rotating-frame TCMT, we use a
slow modulation trick: pump = constant (rotating-frame DC), signal = small
amplitude at frequency Omega (in the rotating frame, signal oscillates at
Omega). The Kerr cross-term i alpha_3 |a_1|^2 a_1 generates components at
all combinations of Omega; the idler appears at -Omega in the rotating frame.

Output: |idler / signal|^2 versus pump intensity. Architecture ratio is
(1+R)^2 in the small-signal limit; quadratic in R.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from core import tcmt_rhs, alpha3_casc_full, adjacent_save


def measure_fwm_efficiency(beta, gamma1, gamma2, dw_FM, dw_SH,
                            alpha3_native, s_pump, s_signal, Omega_signal):
    """Drive with pump + small signal sideband, extract idler amplitude.

    Drive: s_+(t) = s_pump + s_signal * exp(-i Omega_signal t)
    In the FM rotating frame the pump is DC at delta_p=dw_FM and the signal
    has rotating-frame frequency dw_FM - Omega_signal.

    The Kerr-driven idler appears at rotating-frame frequency dw_FM + Omega_signal.
    Both pump and signal must be within the FM linewidth ~ gamma_1.

    Returns |a_1(idler)|^2 / |s_signal|^2 -- the signal-to-idler conversion ratio.
    """
    # Time grid
    T_settle = 30.0 / min(gamma1, gamma2)
    T_total = T_settle + 40.0 * 2*np.pi / Omega_signal
    t_eval = np.linspace(T_settle, T_total, 4000)

    def s_in_func(t):
        return s_pump + s_signal * np.exp(-1j * Omega_signal * t)

    sol = solve_ivp(
        tcmt_rhs, [0, T_total], [0.0, 0.0, 0.0, 0.0],
        args=(beta, gamma1, gamma2, dw_FM, dw_SH, alpha3_native, s_in_func),
        rtol=1e-9, atol=1e-12, method='DOP853',
        t_eval=t_eval, max_step=0.5/max(abs(Omega_signal), 1.0),
    )

    a1 = sol.y[0] + 1j * sol.y[1]
    # Subtract the DC (pump-driven) component
    a1_dc = np.mean(a1)
    a1_ac = a1 - a1_dc

    # FFT to find spectral components at +/- Omega_signal
    N = len(t_eval)
    dt = t_eval[1] - t_eval[0]
    fft = np.fft.fft(a1_ac) / N
    freqs = np.fft.fftfreq(N, dt) * 2 * np.pi

    # Signal: rotating-frame freq = -Omega_signal (the input signal)
    # Idler: rotating-frame freq = +Omega_signal (generated by FWM)
    idx_signal = np.argmin(np.abs(freqs - (-Omega_signal)))
    idx_idler  = np.argmin(np.abs(freqs - (+Omega_signal)))
    A_signal = abs(fft[idx_signal])
    A_idler = abs(fft[idx_idler])

    return A_idler, A_signal, A_idler / max(A_signal, 1e-30)


def figure_fwm_comparison(savepath=None):
    gamma1 = 1.0
    gamma2 = 1.0
    dw_FM = 0.0          # pump on FM resonance
    dw_SH = -10.0        # safely adiabatic, cascade self-focusing (alpha_3_casc > 0)
    Omega = 0.3 * gamma1 # signal offset, well within FM linewidth
    s_signal = 0.005     # weak signal

    # Choose alpha_3 and beta so R = 2 for the high-cascade case
    beta_high = 2.0
    alpha_3_casc_value = abs(alpha3_casc_full(beta_high, gamma2, dw_SH))
    # Target R = 2: alpha_3_native = alpha_3_casc / 2
    R_target = 2.0
    alpha3_native = alpha_3_casc_value / R_target

    # Sweep pump power, three architectures
    s_pump_arr = np.logspace(-2, 0.0, 12)  # smaller range, fewer points for speed

    results_A = []   # native only
    results_AB = []  # combined

    for s_p in s_pump_arr:
        # A: native only
        A_idl_A, A_sig_A, ratio_A = measure_fwm_efficiency(
            beta=0.0, gamma1=gamma1, gamma2=gamma2, dw_FM=dw_FM, dw_SH=dw_SH,
            alpha3_native=alpha3_native, s_pump=s_p, s_signal=s_signal,
            Omega_signal=Omega)
        results_A.append(ratio_A**2)  # squared = power ratio

        # A+B: combined
        A_idl_AB, A_sig_AB, ratio_AB = measure_fwm_efficiency(
            beta=beta_high, gamma1=gamma1, gamma2=gamma2, dw_FM=dw_FM, dw_SH=dw_SH,
            alpha3_native=alpha3_native, s_pump=s_p, s_signal=s_signal,
            Omega_signal=Omega)
        results_AB.append(ratio_AB**2)

    eta_A = np.array(results_A)
    eta_AB = np.array(results_AB)

    # Predicted ratio: (1+R)^2 if cascade & native add (constructive)
    predicted_ratio = (1 + R_target)**2

    fig, axes = plt.subplots(1, 2, figsize=(12.5, 4.5))

    # Panel (a): conversion efficiency vs pump
    ax = axes[0]
    ax.loglog(s_pump_arr**2, eta_A, 'o', color='C0', ms=7, mfc='white', mew=1.5,
              label='A (native only)')
    ax.loglog(s_pump_arr**2, eta_AB, '^', color='C2', ms=7, mfc='white', mew=1.5,
              label='A+B (cascade + native)')
    # Predicted scaling: eta ~ |alpha_3_eff|^2 |a_pump|^4 ~ |alpha_eff|^2 (s_pump^2)^2
    a_pump_sq = (4/gamma1) * s_pump_arr**2  # linear cavity build-up
    eta_A_pred = (8 * alpha3_native / gamma1**2)**2 * s_pump_arr**4
    eta_AB_pred = ((8 * (alpha3_native + alpha_3_casc_value) / gamma1**2))**2 * s_pump_arr**4
    ax.loglog(s_pump_arr**2, eta_A_pred, '-', color='C0', alpha=0.5, lw=1)
    ax.loglog(s_pump_arr**2, eta_AB_pred, '-', color='C2', alpha=0.5, lw=1)
    ax.set_xlabel(r'Pump power $|s_+^{\rm pump}|^2$')
    ax.set_ylabel(r'FWM efficiency $|s_-^{\rm idler}/s_+^{\rm sig}|^2$')
    ax.set_title(r'(a) FWM conversion: $\eta_{\rm FWM}\propto|\alpha_3^{\rm eff}|^2|s_+|^4$')
    ax.legend(loc='lower right', framealpha=0.95)
    ax.grid(True, which='both', alpha=0.3)

    # Panel (b): ratio (A+B) / A vs pump
    ax = axes[1]
    ratio = eta_AB / np.maximum(eta_A, 1e-30)
    ax.semilogx(s_pump_arr**2, ratio, 'D-', color='C4', ms=7, mfc='white', mew=1.5,
                label=r'$\eta_{\rm FWM}^{\rm A+B}/\eta_{\rm FWM}^{\rm A}$ (TCMT)')
    ax.axhline(predicted_ratio, color='k', ls='--', lw=1.2,
               label=fr'Predicted $(1+R)^2 = {predicted_ratio:.1f}$')
    ax.axhline(1 + R_target, color='gray', ls=':', lw=1,
               label=fr'For comparison: $(1+R) = {1+R_target:.1f}$ (phase ratio)')
    ax.set_xlabel(r'Pump power $|s_+^{\rm pump}|^2$')
    ax.set_ylabel(r'Architecture ratio $\eta^{\rm A+B}_{\rm FWM}/\eta^{\rm A}_{\rm FWM}$')
    ax.set_title(r'(b) FWM is the most differentiating observable')
    ax.legend(loc='lower right', framealpha=0.95)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(0, predicted_ratio * 1.4)

    fig.suptitle(r'Four-wave mixing: native vs combined  '
                 fr'($R={R_target}$, $\Omega/\gamma_1={Omega:.2f}$, $\Delta_{{\rm SH}}/\gamma_2={dw_SH:g}$)',
                 fontsize=11, y=1.02)
    fig.tight_layout()
    if savepath:
        adjacent_save(fig, savepath)
    return fig


if __name__ == '__main__':
    figure_fwm_comparison(savepath='G2_B3_fwm_comparison.png')
