"""Cascade-only AM modulator: time-dependent Delta_omega drives FM-port
amplitude modulation.

Tier 2, item 6 of the note's Section 13. The cascade has a free knob
that native-Kerr does not: the SH-cavity detuning Delta_omega. Driving
Delta_omega(t) = Delta_omega_0 + delta_Omega sin(Omega_mod t) -- via
electro-optic, thermo-optic, or piezoelectric actuation of the SH
cavity -- periodically modulates the cascaded effective Kerr coefficient

    alpha_3_casc(Delta_omega) = -|beta|^2 Delta_omega / [Delta_omega^2 + (gamma_2/2)^2]

and hence modulates the FM-port transmission |s_-/s_+|^2 at fixed pump
power. Native-Kerr cavities have no analogous mechanism: the bulk
chi^(3) is not detuning-dependent.

The modulator transfer function rolls off when Omega_mod exceeds the
cascaded coefficient's own bandwidth ~ gamma_2 (the same sum rule that
limits the cascaded Kerr response to slow modulations of the pump
intensity, applied here to modulations of the SH cavity itself).

Two panels:
  (a) Time trace of |s_-(t)|^2 at one Omega_mod, showing the AM
      sidebands generated by the Delta_omega modulation. Native (beta=0)
      shows no AM at all -- the FM transmission is constant despite
      the SH cavity being modulated.
  (b) AM modulation depth vs Omega_mod. Cascade has a Lorentzian-like
      transfer function rolling off at ~gamma_2; native is identically zero.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from style import apply_style
apply_style()
import numpy as np

from params import TCMTParams
from tcmt import integrate

HERE = Path(__file__).resolve().parent
FIG_DIR = HERE / "figures"


def domega_modulated(D0: float, dOmega: float, Omega_mod: float):
    def f(t):
        return D0 + dOmega * np.sin(Omega_mod * t)
    return f


def integrate_with_modulated_domega(p_base: TCMTParams, s_p: float,
                                    Omega_mod: float, dOmega: float,
                                    t_settle: float = 200.0,
                                    n_periods: int = 30, n_per_period: int = 60):
    """Run TCMT with sinusoidally-modulated SH detuning; return the
    quasi-periodic steady-state |s_-(t)|^2 time trace."""
    T_mod = 2 * np.pi / Omega_mod
    t_total = t_settle + n_periods * T_mod
    N = n_periods * n_per_period
    t_eval = t_settle + np.arange(N) * T_mod * n_periods / N

    # Build a new params with a time-dependent Domega
    p = TCMTParams(
        Domega=domega_modulated(p_base.Domega, dOmega, Omega_mod),
        gamma1=p_base.gamma1, gamma1_rad=p_base.gamma1_rad,
        alpha3=p_base.alpha3, delta1=p_base.delta1, beta=p_base.beta,
    )
    sol = integrate(p, s_p, (0.0, t_total), t_eval=t_eval,
                    max_step=min(0.3, T_mod / 30))
    a1 = sol.a[0]
    s_out = -s_p + np.sqrt(p_base.gamma1_rad) * a1
    return sol.t, s_out


def main():
    # Realistic LiNbO3 design point
    base = dict(Domega=2.0, gamma1=10.0, gamma1_rad=5.0,
                alpha3=0.0, delta1=0.0)
    p_nat = TCMTParams(beta=0.0, **base)
    p_cas = TCMTParams(beta=1.0, **base)

    # Use small s_p and small dOmega for clean linear response: at higher
    # s_p the cascade-saturation nonlinearity washes out the AC peak's
    # contrast against the DC level. With these params the AC peak at
    # Omega_mod = Delta omega_0 is ~2x the DC modulation depth.
    s_p = 0.5        # small-signal regime
    dOmega = 0.1     # SH-detuning modulation depth (units of gamma_2)

    # Layout: left half is a vertically-stacked pair of subplots (drive +
    # response); right half is the transfer-function panel.  This avoids
    # the twin-axis overlap of the old layout.
    fig = plt.figure(figsize=(13.5, 5.2))
    gs = fig.add_gridspec(
        2, 2,
        width_ratios=[1.0, 1.05],
        height_ratios=[1.0, 2.0],
        wspace=0.30, hspace=0.10,
    )
    ax_drive = fig.add_subplot(gs[0, 0])     # top-left: Delta omega(t)
    ax_resp  = fig.add_subplot(gs[1, 0], sharex=ax_drive)   # bottom-left: T(t)
    axB      = fig.add_subplot(gs[:, 1])     # right: transfer function

    # ---- Panel (a): time trace at one modulation frequency ----
    Omega_mod_demo = 0.3   # well inside cascade BW
    t_n, sout_n = integrate_with_modulated_domega(p_nat, s_p, Omega_mod_demo, dOmega)
    t_c, sout_c = integrate_with_modulated_domega(p_cas, s_p, Omega_mod_demo, dOmega)
    T_demo = 2 * np.pi / Omega_mod_demo

    # transmissions |s_-(t)|^2 / |s_+|^2
    Tn = np.abs(sout_n) ** 2 / s_p ** 2
    Tc = np.abs(sout_c) ** 2 / s_p ** 2

    # Restrict to last 3 modulation periods for clarity
    mask = t_n >= t_n[-1] - 3 * T_demo
    t_show = t_n[mask] - t_n[mask][0]
    Dom_t = p_cas.Domega + dOmega * np.sin(Omega_mod_demo * (t_n[mask]))

    # (a1) Drive: Delta omega(t)
    ax_drive.plot(t_show, Dom_t, color="0.30", lw=1.6)
    ax_drive.set_ylabel(r"$\Delta\omega(t)/\gamma_2$", fontsize=10)
    ax_drive.grid(True, alpha=0.3)
    ax_drive.set_title(rf"(a) Drive $\Delta\omega(t)$ and response, "
                       rf"$\Omega_{{\rm mod}}/\gamma_2 = {Omega_mod_demo}$",
                       fontsize=11)
    ax_drive.tick_params(axis="x", labelbottom=False)
    # tight y limits so the small modulation is visible
    pad = 0.05 * dOmega
    ax_drive.set_ylim(p_cas.Domega - dOmega - pad, p_cas.Domega + dOmega + pad)

    # (a2) Response: native (flat) and cascade (modulated)
    ax_resp.plot(t_show, Tn[mask], color="C2", lw=1.8,
                 label=r"native ($\beta = 0$)")
    ax_resp.plot(t_show, Tc[mask], color="C0", lw=2.0,
                 label=r"cascade ($\beta = 1$)")
    ax_resp.set_xlabel(r"$t \cdot \gamma_2$  (3 modulation periods)")
    ax_resp.set_ylabel(r"$|s_-(t)|^2 / |s_+|^2$", fontsize=10)
    ax_resp.legend(loc="upper right", fontsize=9.5, framealpha=0.95)
    ax_resp.grid(True, alpha=0.3)

    # ---- Panel (b): AM modulation depth vs Omega_mod -----------
    # Use absolute peak-to-peak of |s_-|^2/|s_+|^2.  Two features expected:
    #   (i) low-pass roll-off above Omega_mod ~ gamma_2/2 (cascaded
    #       coefficient stops tracking),
    #   (ii) RESONANT AC PEAK at Omega_mod ~ |Delta omega_0|: the
    #       modulation sideband hits the SH resonance, maximising the
    #       cascade back-action on the FM.
    Omega_low  = np.geomspace(0.03, 1.0, 12)
    Omega_peak = np.linspace(1.2, 3.5, 14)
    Omega_high = np.geomspace(4.0, 50.0, 12)
    Omega_mod_grid = np.unique(np.concatenate([Omega_low, Omega_peak, Omega_high]))

    depth_nat = np.zeros_like(Omega_mod_grid)
    depth_cas = np.zeros_like(Omega_mod_grid)
    for i, Om in enumerate(Omega_mod_grid):
        _, sout_n = integrate_with_modulated_domega(p_nat, s_p, Om, dOmega)
        _, sout_c = integrate_with_modulated_domega(p_cas, s_p, Om, dOmega)
        Tn_i = np.abs(sout_n) ** 2 / s_p ** 2
        Tc_i = np.abs(sout_c) ** 2 / s_p ** 2
        depth_nat[i] = (Tn_i.max() - Tn_i.min()) / 2
        depth_cas[i] = (Tc_i.max() - Tc_i.min()) / 2

    floor = 1e-13
    axB.loglog(Omega_mod_grid, depth_cas, "s-", color="C0", ms=5,
               mfc="white", mew=1.3, lw=1.4, label=r"cascade ($\beta = 1$)")
    axB.loglog(Omega_mod_grid, np.maximum(depth_nat, floor), "o-",
               color="C2", ms=3.5, mfc="C2", mew=0, lw=1.0, alpha=0.85,
               label=r"native ($\beta = 0$): at numerical floor")

    # Marker vertical lines and short labels at the top of the panel
    y_top = 0.5     # axes-fraction y for marker labels
    axB.axvline(0.5, color="0.55", ls="-.", lw=0.9)
    axB.text(0.5, y_top, r"$\gamma_2/2$" + "\n(low-pass)",
             transform=axB.get_xaxis_transform(),
             color="0.30", fontsize=9, ha="center", va="bottom",
             bbox=dict(facecolor="white", edgecolor="0.7",
                       boxstyle="round,pad=0.25", alpha=0.85))
    axB.axvline(p_cas.Domega, color="C3", ls=":", lw=1.2)
    axB.text(p_cas.Domega, y_top, r"$|\Delta\omega_0|$" + "\n(AC peak)",
             transform=axB.get_xaxis_transform(),
             color="C3", fontsize=9, ha="center", va="bottom",
             bbox=dict(facecolor="white", edgecolor="C3",
                       boxstyle="round,pad=0.25", alpha=0.85))

    # Quantitative peak/DC enhancement annotation
    idx_peak = int(np.argmax(depth_cas))
    idx_dc = int(np.argmin(Omega_mod_grid))
    boost = depth_cas[idx_peak] / depth_cas[idx_dc]
    axB.text(0.97, 0.04,
             rf"peak / DC enhancement: ${boost:.2f}\times$",
             transform=axB.transAxes,
             fontsize=9, ha="right", va="bottom",
             bbox=dict(facecolor="white", edgecolor="0.6",
                       boxstyle="round,pad=0.3", alpha=0.95))

    axB.set_xlabel(r"$\Omega_{\rm mod}/\gamma_2$  (modulation frequency)")
    axB.set_ylabel(r"peak-to-peak amplitude  $(T_{\max} - T_{\min})/2$")
    axB.set_title(r"(b) Modulator transfer function")
    axB.grid(True, which="both", alpha=0.3)
    axB.legend(loc="upper left", fontsize=9.5, framealpha=0.95)
    # Cap y-range so the native-at-floor line doesn't blow open the axis
    axB.set_ylim(max(depth_cas.min() * 0.3, 1e-7), depth_cas.max() * 3)

    fig.suptitle(
        rf"AM modulator via $\Delta\omega(t)$  "
        rf"($\Delta\omega_0 = 2\gamma_2$, $\delta\Omega = {dOmega}\,\gamma_2$, "
        rf"$s_+ = {s_p}$)",
        fontsize=12, y=1.00,
    )
    fig.tight_layout()
    FIG_DIR.mkdir(exist_ok=True)
    out = FIG_DIR / "am_modulator"
    fig.savefig(out.with_suffix(".png"), dpi=150)
    fig.savefig(out.with_suffix(".pdf"))
    print(f"wrote {out}.{{png,pdf}}")
    for Om_ref in [0.1, 1.0, 10.0]:
        idx = np.argmin(abs(Omega_mod_grid - Om_ref))
        print(f"  Omega_mod = {Omega_mod_grid[idx]:5.2f} gamma_2 : "
              f"native depth = {depth_nat[idx]:.2e},  "
              f"cascade depth = {depth_cas[idx]:.3e}")
    plt.close(fig)


if __name__ == "__main__":
    main()
